---
- name: Create tomcat AWS infrastructure
  hosts: localhost
  connection: local
  roles:
    - tomcat_aws

- name: deploy tomcat service
  hosts: webservers
  become: yes
  remote_user: ec2-user
  become_method: sudo
  environment: 
    ANSIBLE_CONFIG: "ansible.cfg"
  roles:
    - tomcat	
