#---------------Ansible EC2 Creation----------------
---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-5b673c34  # Redhat
      keypair: sonal-instance # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "{{ my_access_key }}"
         aws_secret_key: "{{ my_secret_key }}"
         group: launch-wizard-3  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default how many machines i want to create
         count_tag:
            Name: "EC2_Thru_Ansible"
         instance_tags:
            Name: "EC2_Thru_Ansible"
         vpc_subnet_id: "subnet-76b0e91e"
         assign_public_ip: yes
      register: ec2

    - name: debugging the output
      debug: var=ec2
#boto required 

