---

- host: localhost
  connection: local

  vars: 
    fruits:
      - Apple
      - Orange
      - Banana
      - Grapes

  tasks:
    - command: echo "{{ item }}"
      with_items: '{{ fruits }}'

    - debug: msg="{{ item }}"
      with_items: '{{ fruits }}'

... 
